config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  resources :financial_planners
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/financial_planner.rb
class FinancialPlanner < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
        render html: "hello world"
    end
end

app/controllers/financial_planners_controller.rb
class FinancialPlannersController < ApplicationController
  before_action :set_financial_planner, only: [:show, :edit, :update, :destroy]

  # GET /financial_planners
  # GET /financial_planners.json
  def index
    @financial_planners = FinancialPlanner.all
  end

  # GET /financial_planners/1
  # GET /financial_planners/1.json
  def show
  end

  # GET /financial_planners/new
  def new
    @financial_planner = FinancialPlanner.new
  end

  # GET /financial_planners/1/edit
  def edit
  end

  # POST /financial_planners
  # POST /financial_planners.json
  def create
    @financial_planner = FinancialPlanner.new(financial_planner_params)

    respond_to do |format|
      if @financial_planner.save
        format.html { redirect_to @financial_planner, notice: 'Financial planner was successfully created.' }
        format.json { render :show, status: :created, location: @financial_planner }
      else
        format.html { render :new }
        format.json { render json: @financial_planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /financial_planners/1
  # PATCH/PUT /financial_planners/1.json
  def update
    respond_to do |format|
      if @financial_planner.update(financial_planner_params)
        format.html { redirect_to @financial_planner, notice: 'Financial planner was successfully updated.' }
        format.json { render :show, status: :ok, location: @financial_planner }
      else
        format.html { render :edit }
        format.json { render json: @financial_planner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /financial_planners/1
  # DELETE /financial_planners/1.json
  def destroy
    @financial_planner.destroy
    respond_to do |format|
      format.html { redirect_to financial_planners_url, notice: 'Financial planner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_financial_planner
      @financial_planner = FinancialPlanner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def financial_planner_params
      params.require(:financial_planner).permit(:name, :email, :phone_number)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/financial_planners_helper.rb
module FinancialPlannersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/financial_planners/_form.html.erb
<%= form_with(model: financial_planner, local: true) do |form| %>
  <% if financial_planner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(financial_planner.errors.count, "error") %> prohibited this financial_planner from being saved:</h2>

      <ul>
        <% financial_planner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/financial_planners/edit.html.erb
<h1>Editing Financial Planner</h1>

<%= render 'form', financial_planner: @financial_planner %>

<%= link_to 'Show', @financial_planner %> |
<%= link_to 'Back', financial_planners_path %>

app/views/financial_planners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Financial Planners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @financial_planners.each do |financial_planner| %>
      <tr>
        <td><%= financial_planner.name %></td>
        <td><%= financial_planner.email %></td>
        <td><%= financial_planner.phone_number %></td>
        <td><%= link_to 'Show', financial_planner %></td>
        <td><%= link_to 'Edit', edit_financial_planner_path(financial_planner) %></td>
        <td><%= link_to 'Destroy', financial_planner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Financial Planner', new_financial_planner_path %>

app/views/financial_planners/new.html.erb
<h1>New Financial Planner</h1>

<%= render 'form', financial_planner: @financial_planner %>

<%= link_to 'Back', financial_planners_path %>

app/views/financial_planners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @financial_planner.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @financial_planner.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @financial_planner.phone_number %>
</p>

<%= link_to 'Edit', edit_financial_planner_path(@financial_planner) %> |
<%= link_to 'Back', financial_planners_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone_number %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>